### PR TITLE
Swift 3.0

### PR DESCRIPTION
**Pull request by cameronehrlich**

### CODE REVIEW

**Comment by cameronehrlich** [comment]
@freak4pc all you need to do is accept the merge and make a `1.4` tag!

**Comment by freak4pc** [comment]
Hey @cameronehrlich ! First of all thank you very much for your contribution ! 
I've been a bit swamped with work so didn't get a chance to see some of the posts here.

Did you notice thought there is actually a swift3 branch ? 
It is almost identical to the one you published. 

Would you be fine with me closing this pull request and just fixing up the swift3 branch and moving it to master? Or if you prefer, you can make some of the fixes on the swift3 branch, if easier. 

I don't want to dismiss your contribution of course, as I said, it's highly appreciated, but most of migration has already been done in the other branch :)

**Comment by freak4pc** [comment]
I've moved the Swift 3 code to master, did some last fixes and updated README & CHANGELOG.

Also bumped the pod version: https://cocoapods.org/pods/UIView+Positioning

Many thanks for your help, much appreciated !

**Comment by cameronehrlich** [comment]
@freak4pc no worries at all!  I didn't see the other branch! haha
I was updating a project last night, and ended up fixing the compatibility issues on my own.  I figured I should contribute them back!
Glad it's been updated!

**Comment by cameronehrlich** [comment]
Oh, one other thing...
I was gonna suggest that you add cocoapod installation instruction like somewhere on the README.
Totally not necessary I know, but it helps people know its available there.

e.g.

> Cocoapods Installation:

```objective c
pod 'UIView+Positioning', '~> 1.3'
```
Cheers 🍻 !

**Comment by freak4pc** [comment]
Hey Cameron, sounds great! If you want to add itI'll merge ;-)

**Pull request closed without merging**
